# Generated by Django 4.2.11 on 2024-11-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
